// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuangKampus.Backend.Data;

#nullable disable

namespace RuangKampus.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209065422_InitialSeeding")]
    partial class InitialSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RuangKampus.Backend.Models.RoomLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomLoans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorrowerName = "Budi Santoso",
                            EndTime = new DateTime(2026, 2, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Purpose = "Pengerjaan Tugas Akhir",
                            RoomName = "Lab Komputer 1",
                            StartTime = new DateTime(2026, 2, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        },
                        new
                        {
                            Id = 2,
                            BorrowerName = "Siti Aminah",
                            EndTime = new DateTime(2026, 2, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Purpose = "Seminar Proposal",
                            RoomName = "Aula Utama",
                            StartTime = new DateTime(2026, 2, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            BorrowerName = "Himpunan Mahasiswa",
                            EndTime = new DateTime(2026, 2, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Purpose = "Rapat Bulanan",
                            RoomName = "Ruang Rapat 1",
                            StartTime = new DateTime(2026, 2, 12, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        },
                        new
                        {
                            Id = 4,
                            BorrowerName = "Dosen Tamu",
                            EndTime = new DateTime(2026, 2, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Purpose = "Kuliah Umum",
                            RoomName = "Auditorium",
                            StartTime = new DateTime(2026, 2, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 5,
                            BorrowerName = "Admin",
                            EndTime = new DateTime(2026, 2, 14, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Purpose = "Testing Sistem",
                            RoomName = "Studio Musik",
                            StartTime = new DateTime(2026, 2, 14, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Rejected"
                        });
                });

            modelBuilder.Entity("RuangKampus.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "user123",
                            Role = "User",
                            Username = "mahasiswa"
                        },
                        new
                        {
                            Id = 3,
                            Password = "12345",
                            Role = "User",
                            Username = "Budi Santoso"
                        },
                        new
                        {
                            Id = 4,
                            Password = "12345",
                            Role = "User",
                            Username = "Siti Aminah"
                        },
                        new
                        {
                            Id = 5,
                            Password = "12345",
                            Role = "User",
                            Username = "Himpunan Mahasiswa"
                        },
                        new
                        {
                            Id = 6,
                            Password = "12345",
                            Role = "User",
                            Username = "Dosen Tamu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
